services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    secrets:
      - db_password
    networks:
      - app-network

  app:
    build:
      context: ./app
    container_name: flask-app
    environment:
      DATABASE_URL: postgres://myuser:@postgres-db:5432/mydatabase
    volumes:
      - ./app:/usr/src/app
    networks:
      - app-network
    depends_on:
      - db

volumes:
  db_data:

networks:
  app-network:

secrets:
  db_password:
    file: ./secrets/db_password.txt